### ISSUE TITLE
Final weight for ISIC

### ISSUE THREAD

**Issue by avisekiit** [fabioperez/skin-data-augmentation#1]
Could you kindly release the final model weights for ISIC classification that you mentioned

**Comment by fabioperez** [comment]
Which model? In the paper I trained several models. I don't know if I still have the saved weights for everything, but you can reproduce the training following the README.

**Comment by avisekiit** [comment]
Practically speaking, I am okay with any of the model. I am just playing around with the dataset and any pretrained model would be good for me.

Though I see you have done a meticulous and appreciable job training with inceptionv4, resnet152, densenet161, senet154

**Comment by fabioperez** [comment]
Here is the best ResNet model: https://drive.google.com/file/d/1xK3HYOY8Ks7MUQnGaSy8VnHJl-fVtAKF/view?usp=sharing

**Comment by ahmadmughees** [comment]
hi @fabioperez 
I was exploring your model and realized that you have used 2 neuron at the output linear classifier layer, but incase of ISIC, that was a three-class classification challenge. Can you explain a bit please? 

Thanks.
