### ISSUE TITLE
what shouldi change if my groundtruth is images not cvs files 

### ISSUE THREAD

**Issue by Ng-ms** [fabioperez/skin-data-augmentation#2]

**Comment by fabioperez** [comment]
Just change the datasets [here](https://github.com/fabioperez/skin-data-augmentation/blob/91c6109796b23b0bf174632937474853b9559460/train.py#L169). You can use [ImageFolder](https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder), for instance.
